---
# Example:
#
#   ansible-playbook -K linux-desktop-virtualbox.yml

- name: Install FreeTube for Linux-Desktop
  hosts: localhost
  become: yes
  tasks:
    - name: "freetube: Get latest FreeTube version"
      shell: curl -sS https://api.github.com/repos/FreeTubeApp/FreeTube/releases | jq -r '.[0].tag_name'
      register: freetube_latest_version
      changed_when: false
    - name: "freetube: Get download URL of latest FreeTube version"
      shell: curl -sS https://api.github.com/repos/FreeTubeApp/FreeTube/releases | jq -r '.[0].assets[] | select(.browser_download_url | test(".*amd64.deb$")) | .browser_download_url'
      register: freetube_download_url
      changed_when: false
    - name: "freetube: Install FreeTube"
      ansible.builtin.apt:
        deb: "{{ freetube_download_url.stdout }}"
