---
# Example:
#
#   ansible-playbook -K linux-desktop-debian-sbuild.yml

- name: Install Debian build environment (sbuild with unshare / mmdebstrap) for Linux-Desktop
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Debian build environment selection is installed
      ansible.builtin.apt:
        name:
          - apt-cacher-ng
          - autopkgtest
          - debvm
          - git-buildpackage
          - mmdebstrap
          - sbuild
          - uidmap
