---
# Example:
#
#   ansible-playbook -K linux-desktop-devops.yml

- name: Bootstrap DevOps Tools for Linux-Desktop
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Linux-Desktop DevOps package selection is installed
      apt:
        name:
          - nmap
          - python3-sphinx
          - smbclient
          # podman:
          - golang-github-containernetworking-plugin-dnsname
          - podman-docker
          - podman-compose
          - slirp4netns
          - uidmap
        state: present
