---
# Example:
#
#   ansible-playbook -K linux-desktop-office.yml

- name: Install GUI/Office software for Linux-Desktop
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Linux-Desktop GUI/Office package selection is installed
      ansible.builtin.apt:
        name:
          - autokey-gtk
          - curl
          - chromium
          - diodon
          - hunspell-de-at
          - imagemagick-6.q16
          - doublecmd-gtk
          - freerdp2-x11
          - gnupg
          - gimp
          - gucharmap
          - hamster-time-tracker
          - keepassxc
          - libreoffice
          - mumble
          - mpv
          - network-manager-openvpn-gnome
          - pdftk-java
          - python3-qrtools
          - qrencode
          - syncthing
          - tesseract-ocr
          - tesseract-ocr-deu
          - thunderbird
          - vim-gtk3
          - xclip
        state: present

    - name: Install font related packages
      apt:
        name:
          - fonts-3270
          - fonts-cantarell
          - fonts-crosextra-caladea
          - fonts-crosextra-carlito
          - fonts-dejavu
          - fonts-droid-fallback
          - fonts-fantasque-sans
          - fonts-firacode
          - fonts-font-awesome
          - fonts-freefont-otf
          - fonts-freefont-ttf
          - fonts-inconsolata
          - fonts-lato
          - fonts-liberation
          - fonts-liberation2
          - fonts-linuxlibertine
          - fonts-lmodern
          - fonts-mathjax
          - fonts-noto
          - fonts-noto-color-emoji
          - fonts-noto-mono
          - fonts-opensymbol
          - fonts-powerline
          - fonts-quicksand
          - fonts-roboto
          - fonts-sil-gentium
          - fonts-sil-gentium-basic
          - fonts-symbola
          - fonts-texgyre
          - fonts-urw-base35
          - ttf-bitstream-vera
          - ttf-mscorefonts-installer
          # non-free
          # - fonts-ubuntu
        state: present
