---
# Example:
#
#   ansible-playbook -K linux-desktop-audacity.yml

- name: Install Audacity for Linux-Desktop
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Linux-Desktop Audacity package selection is installed
      apt:
        name:
          - audacity
        state: present
