---
# Example:
#
#   ansible-playbook -K linux-desktop-vscodium.yml
#
# See: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/blob/master/README.md

- name: Install VSCodium for Linux-Desktop
  hosts: localhost
  become: yes
  roles:
    - role: aptrepo
      aptrepo_apt_key_url: "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg"
      aptrepo_apt_key_file: "vscodium-archive-keyring.gpg"
      aptrepo_apt_repository: "https://download.vscodium.com/debs"
      aptrepo_apt_release: "vscodium"
      aptrepo_apt_component: "main"
      aptrepo_apt_sources_file: "vscodium.list"

  tasks:
    - name: "vscodium: Install VSCodium"
      ansible.builtin.apt:
        name: codium
        state: present
