---
# Example:
#
#   ansible-playbook -K linux-desktop-samba.yml

- name: Install Samba for Linux-Desktop
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Linux-Desktop Samba package selection is installed
      apt:
        name:
          - samba
        state: present
