---
# Example:
#
#   ansible-playbook -K linux-desktop-extended-base.yml

- name: Bootstrap extended base for Linux-Desktop
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Linux-Desktop extended base package selection is installed
      apt:
        name:
          - apt-file
          - aria2
          - ddgr
          - git-crypt
          - git-filter-repo
          - network-manager-openvpn
          - nnn
          - python3-venv
          - recode
          - timewarrior
          - tasksh
          - taskwarrior
          - uptimed
          - vim-airline
          - vim-fugitive
          - vim-voom
          - wifi-qr
          - yt-dlp
        state: present
    - name: Get stat of starship binary
      stat:
        path: /usr/local/bin/starship
      register: starship_stat
      changed_when: false
    - name: Get installed starship version
      shell: /usr/local/bin/starship --version | head -1 | awk '{ print "v"$2 }'
      register: starship_version
      when: starship_stat.stat.exists
      changed_when: false
    - name: Get latest starship version
      shell: curl -sS https://api.github.com/repos/starship/starship/releases/latest | jq -r '.name'
      register: starship_latest_version
      when: starship_stat.stat.exists
      changed_when: false
    - name: Install latest starship version
      shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
      when:
        - not starship_stat.stat.exists or (starship_version.stdout != starship_latest_version.stdout)
