---
# Example:
#
#   ansible-playbook -K linux-desktop-virtualbox.yml

- name: Install VirtualBox (upstream) for Linux-Desktop
  hosts: localhost
  become: yes
  vars:
    virtualbox_version: "7.2"
    virtualbox_extpack_version: "7.2.6"
  roles:
    - role: aptrepo
      aptrepo_apt_key_url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
      aptrepo_apt_key_file: "oracle_vbox_2016.asc"
      aptrepo_apt_repository: "https://download.virtualbox.org/virtualbox/debian"
      aptrepo_apt_release: "{{ ansible_distribution_release }}"
      aptrepo_apt_component: "contrib"
      aptrepo_apt_sources_file: "virtualbox.list"

  tasks:
    - name: "virtualbox: Install VirtualBox + Linux Kernel Headers"
      ansible.builtin.apt:
        name:
          - "virtualbox-{{ virtualbox_version }}"
          - "linux-headers-amd64"
        state: present
    # NOTE: VirtualBox Extension Pack needs a reboot or modprobe after VirtualBox has been installed
    - name: "virtualbox: Download VirtualBox Extension Pack"
      ansible.builtin.get_url:
        url: https://download.virtualbox.org/virtualbox/{{ virtualbox_extpack_version }}/Oracle_VirtualBox_Extension_Pack-{{ virtualbox_extpack_version }}.vbox-extpack
        dest: /tmp/Oracle_VirtualBox_Extension_Pack-{{ virtualbox_extpack_version }}.vbox-extpack
        owner: root
        group: root
        mode: 0644
    - name: "virtualbox: Install VirtualBox Extension Pack"
      ansible.builtin.shell: VBoxManage extpack install --accept-license=33d7284dc4a0ece381196fda3cfe2ed0e1e8e7ed7f27b9a9ebc4ee22e24bd23c --replace "/tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_extpack_version }}.vbox-extpack"
