---
# Example:
#
#   ansible-playbook -K linux-desktop-darktable.yml

- name: Install Darktable for Linux-Desktop
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Linux-Desktop Darktable package selection is installed
      apt:
        name:
          - darktable
        state: present
