---
# Example:
#
#   ansible-playbook -K linux-desktop-office.yml

- name: Install GUI/Office software for Linux-Desktop
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Linux-Desktop GUI/Office package selection is installed
      ansible.builtin.apt:
        name:
          - autokey-gtk
          - curl
          - chromium
          - diodon
          - imagemagick-6.q16
          - doublecmd-gtk
          - freerdp2-x11
          - gnupg
          - hamster-time-tracker
          - keepassxc
          - libreoffice
          - mpv
          - network-manager-openvpn-gnome
          - qrencode
          - thunderbird
          - syncthing
          - vim-gtk3
          - xclip
        state: present
