---
# Example:
#
#   ansible-playbook -K linux-desktop-devops.yml

- name: Bootstrap DevOps Tools for Linux-Desktop
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Linux-Desktop DevOps package selection is installed
      apt:
        name:
          - codespell
          - fd-find
          - gitk
          - nmap
          - pre-commit
          - python3-sphinx
          - smartmontools
          - smbclient
          - strace
          - wakeonlan
          - whois
          # podman:
          - golang-github-containernetworking-plugin-dnsname
          - podman-docker
          - podman-compose
          - slirp4netns
          - uidmap
        state: present
