---
# Example:
#
#   ansible-playbook -K linux-desktop-debian-sbuild.yml

- name: Install Debian build environment (sbuild with unshare / mmdebstrap) for Linux-Desktop
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Debian build environment selection is installed
      ansible.builtin.apt:
        name:
          - apt-cacher-ng
          - autopkgtest
          - build-essential
          - debvm
          - devscripts
          - git-buildpackage
          - libgitlab-api-v4-perl  # needed for salsa cli from devscripts
          - mmdebstrap
          - piuparts
          - qemu-utils
          - quilt
          - sbuild
          - sbuild-debian-developer-setup
          - uidmap
