---
# Example:
#
#   ansible-playbook -K linux-desktop-devops.yml

- name: Bootstrap DevOps Tools for Linux-Desktop
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Linux-Desktop DevOps package selection is installed
      apt:
        name:
          - nmap
          - python3-sphinx
          - smbclient
        state: present
