---
# role: github_install
#
# Description: Install a Debian deb package from Github Release page
#
# Variables:
#
#  - github_install_name: The short name shown in the playbook
#  - github_install_fullname: The full name shown in the playbook
#  - github_install_repos: The full Github repos (i.e. $USER/$REPOSNAME) of the package to be installed
#  - github_install_arch: The architecture of the Debian deb package (defaults to amd64)

- name: "{{ github_install_name }}: Get latest {{ github_install_fullname }} version"
  shell: "curl -sS https://api.github.com/repos/{{ github_install_repos }}/releases/latest | jq -r '.tag_name'"
  register: github_latest_version
  changed_when: false
  check_mode: false
- name: "{{ github_install_name }}: Get download URL of latest {{ github_install_fullname }} version"
  shell: "curl -sS https://api.github.com/repos/{{ github_install_repos }}/releases | jq -r '.[0].assets[] | select(.browser_download_url | test(\".*{{ github_install_arch|default('amd64') }}.deb$\")) | .browser_download_url'"
  register: github_download_url
  changed_when: false
  failed_when: github_download_url.stdout|length == 0
  check_mode: false
- name: "{{ github_install_name }}: Install {{ github_install_fullname }}"
  ansible.builtin.apt:
    deb: "{{ github_download_url.stdout }}"
